import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <div className=" bg-[#202123] p-4 max-w-xs min-h-screen md:min-w-[20rem]">
            <Sidebar />
          </div>
          <div className="bg-[#343541] flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
